name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NPM Package
        run: npm ci

      - name: Install Appcenter
        run: npm install -g appcenter-cli

      - name: Build Android apk
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Move APK to Appium Test Folder
        run: mv android/app/build/outputs/apk/release/app-release.apk appium_test/app-release.apk

      - name: Run Maven
        run: mvn -DskipTests -P prepare-for-upload package
        working-directory: appium_test

      - name: Upload Test to App Center
        run: appcenter test run appium --app "ariefputranto0-gmail.com/Krasmart-Connect" --devices "ariefputranto0-gmail.com/test-device" --app-path "app-release.apk" --test-series "dev" --locale "en_US" --build-dir target/upload --token ${{ secrets.APP_CENTER_TOKEN }}
        working-directory: appium_test

      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: krasmart-connect-apk
          path: '**/*.apk'
